const StoryActionTypes = {
  FETCH_STORIES_START: 'FETCH_STORIES_START',
  FETCH_STORIES_FAILURE: 'FETCH_STORIES_FAILURE',
  FETCH_STORIES_SUCCESS: 'FETCH_STORIES_SUCCESS',
};

export default StoryActionTypes;
