const UserActionTypes = {
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_OUT: 'SIGN_OUT',
  SEARCH_USERS_START: 'SEARCH_USERS_START',
  SEARCH_USERS_FAILURE: 'SEARCH_USERS_FAILURE',
  SEARCH_USERS_SUCCESS: 'SEARCH_USERS_SUCCESS',
  UPDATE_CURRENT_USER: 'UPDATE_CURRENT_USER',
};

export default UserActionTypes;
