const CommentActionTypes = {
  FETCH_POST_COMMENTS_START: 'FETCH_POST_COMMENTS_START',
  FETCH_POST_COMMENTS_FAILURE: 'FETCH_POST_COMMENTS_FAILURE',
  FETCH_POST_COMMENTS_SUCCESS: 'FETCH_POST_COMMENTS_SUCCESS',
  CREATE_COMMENT_START: 'CREATE_COMMENT_START',
  CREATE_COMMENT_FAILURE: 'CREATE_COMMENT_FAILURE',
  CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS',
  DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
};

export default CommentActionTypes;
