const LikeActionTypes = {
  LIKE_POST_START: 'LIKE_POST_START',
  LIKE_POST_FAILURE: 'LIKE_POST_FAILURE',
  LIKE_POST_SUCCESS: 'LIKE_POST_SUCCESS',
  UNLIKE_POST_START: 'UNLIKE_POST_START',
  UNLIKE_POST_FAILURE: 'UNLIKE_POST_FAILURE',
  UNLIKE_POST_SUCCESS: 'UNLIKE_POST_SUCCESS',
  FETCH_USER_LIKES_START: 'FETCH_USER_LIKES_START',
  FETCH_USER_LIKES_FAILURE: 'FETCH_USER_LIKES_FAILURE',
  FETCH_USER_LIKES_SUCCESS: 'FETCH_USER_LIKES_SUCCESS',
};

export default LikeActionTypes;
