const FollowActionTypes = {
  FOLLOW_USER_SUCCESS: 'FOLLOW_USER_SUCCESS',
  UNFOLLOW_USER_SUCCESS: 'UNFOLLOW_USER_SUCCESS',
  FETCH_FOLLOWS_SUCESS: 'FETCH_FOLLOWS_SUCESS',
};

export default FollowActionTypes;
