const PostActionTypes = {
  FETCH_POSTS_START: 'FETCH_POSTS_START',
  FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',
  FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
  FETCH_USER_POSTS_START: 'FETCH_USER_POSTS_START',
  FETCH_USER_POSTS_FAILURE: 'FETCH_USER_POSTS_FAILURE',
  FETCH_USER_POSTS_SUCCESS: 'FETCH_USER_POSTS_SUCCESS',
  FETCH_POST_START: 'FETCH_POST_START',
  FETCH_POST_FAILURE: 'FETCH_POST_FAILURE',
  FETCH_POST_SUCCESS: 'FETCH_POST_SUCCESS',
  CREATE_POST_START: 'CREATE_POST_START',
  CREATE_POST_FAILURE: 'CREATE_POST_FAILURE',
  CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
};

export default PostActionTypes;
